version: '3.3'
services:

  db:
    env_file:
      - .env
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  frontend:
    image: uforick/warmspace_foodgram_frontend:latest
    volumes:
      - result_build:/app/result_build/build

  backend:
    image: uforick/warmspace_foodgram:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    env_file:
    - ./.env

volumes:
  result_build:
  postgres_data:
  static_value:
  media_value: