# Generated by Django 3.0.5 on 2021-07-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210729_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistmodel',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglistmodel',
            name='cart_user_recept_unique',
        ),
    ]
