# Generated by Django 3.2.5 on 2021-07-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_follow_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='FollowModel',
        ),
    ]
